// menu-data.js

export const menuCategories = [
  {
    id: "burgers",
    title: "Burgers",
    items: [
      { name: "Cheese Burger", price: 25 },
      { name: "Double Burger", price: 35 },
      { name: "Chicken Burger", price: 30 },
      { name: "Burger Simple", price: 22 },
    ],
  },
  {
    id: "pizza",
    title: "Nos Pizza",
    items: [
      { name: "Margarita", price: 22 },
      { name: "4 Saisons", price: 40 },
      { name: "Thon", price: 30 },
      { name: "Viande Hachee", price: 33 },
      { name: "Poulet", price: 30 },
      { name: "Fruit de Mer", price: 40 },
      { name: "Nordique", price: 45 },
    ],
  },
  {
    id: "pasta",
    title: "Pasta",
    options: [
      { name: "Penne", extra: 0 },
      { name: "Spaghetti", extra: 0 },
      { name: "Tagliatelle", extra: 5 },
    ],
    items: [
      { name: "Poulet", price: 30 },
      { name: "Viande Hachee", price: 35 },
      { name: "Fruit De Mer", price: 40 },
      { name: "Nordique (Saumon)", price: 45 },
    ],
  },
  {
    id: "fast",
    title: "Plats rapides",
    items: [
      { name: "Brochette Poulet", price: 30 },
      { name: "Brochette Viande Hachee", price: 35 },
      { name: "Plats Mixte", price: 35 },
      { name: "Brochette Poisson", price: 40 },
      { name: "Plat Escalope", price: 30 },
      { name: "Plat Dind", price: 25 },
    ],
    supplements: [
      { name: "Fromage Carre", price: 2 },
      { name: "Fromage Rouge", price: 5 },
      { name: "Cordon Bleu", price: 12 },
    ],
  },
  {
    id: "trad",
    title: "Plats Traditionnelles",
    items: [
      { name: "Mini Pastilla Poulet", price: 40 },
      { name: "Mini Pastilla Fruit de Mer", price: 55 },
      { name: "Soupe de Poisson", price: 20 },
    ],
    supplements: [
      { name: "Thon", price: 5 },
      { name: "Oeuf", price: 3 },
      { name: "Frite", price: 5 },
    ],
  },
  {
    id: "pasticcio",
    title: "Pasticcio",
    items: [
      { name: "Poulet", price: 25 },
      { name: "Viande Hachee", price: 30 },
      { name: "Fruit De Mer", price: 40 },
      { name: "Mixte", price: 35 },
      { name: "Escalope", price: 30 },
      { name: "Shawarma", price: 30 },
    ],
  },
  {
    id: "tacos",
    title: "Nos Tacos",
    hasSizes: true,
    items: [
      { name: "Poulet", prices: { normal: 25, double: 33, fries: 5 } },
      { name: "Mixte", prices: { normal: 30, double: 40, fries: 5 } },
      { name: "Escalope", prices: { normal: 30, double: 40, fries: 5 } },
      { name: "Viande Hachee", prices: { normal: 30, double: 40, fries: 5 } },
      { name: "Sepia", prices: { normal: 30, double: 40, fries: 5 } },
      { name: "Shawarma", prices: { normal: 25, double: 35, fries: 5 } },
      { name: "Fruit de Mer", prices: { normal: 40, double: 50, fries: 5 } },
      { name: "Nordique", prices: { normal: 45, double: 55, fries: 5 } },
    ],
  },
  {
    id: "shawarma",
    title: "Specialite Shawarma",
    items: [
      { name: "Plats Shawarma", price: 30 },
      { name: "Sandwish Shawarma", price: 15 },
      { name: "Sandwish Shawarma Double", price: 25 },
    ],
  },
  {
    id: "chicken",
    title: "Poulet",
    items: [
      { name: "Poulet Rotti", price: 85 },
      { name: "Poulet Complet Simple", price: 110 },
      { name: "Poulet Tout Option", price: 55 },
      { name: "1/2 Poulet avec Salade et Frite", price: 30 },
      { name: "1/4 Poulet avec Salade et Frite", price: 25 },
    ],
  },
  {
    id: "sandwich",
    title: "Sandwich",
    items: [
      { name: "Poulet", price: 15 },
      { name: "Dind", price: 15 },
      { name: "Mixte", price: 20 },
      { name: "Viande Hachee", price: 16 },
      { name: "Sipia", price: 16 },
      { name: "Shawarma", price: 15 },
      { name: "Fruit De Mer", price: 20 },
      { name: "Escalope", price: 16 },
    ],
  },
  {
    id: "panini",
    title: "Panini",
    hasSizes: true,
    items: [
      { name: "Poulet", prices: { normal: 15, double: 25 } },
      { name: "Dind", prices: { normal: 15, double: 25 } },
      { name: "Mixte", prices: { normal: 20, double: 30 } },
      { name: "Viande Hachee", prices: { normal: 16, double: 26 } },
      { name: "Sipia", prices: { normal: 16, double: 26 } },
      { name: "Shawarma", prices: { normal: 15, double: 25 } },
      { name: "Fruit De Mer", prices: { normal: 20, double: 30 } },
      { name: "Escalope", prices: { normal: 16, double: 26 } },
    ],
  },
  {
    id: "special",
    title: "Plats Special",
    items: [
      { name: "Emince poulet", price: 40 },
      { name: "Cordon Bleu", price: 35 },
      { name: "Calamar", price: 60 },
      { name: "Sipia", price: 35 },
    ],
  },
  {
    id: "salads",
    title: "Salades",
    items: [
      { name: "Salade Mexicaine", price: 15 },
      { name: "Salade Normal", price: 10 },
      { name: "Salade Nicoise", price: 17 },
      { name: "Salade Cesar", price: 20 },
      { name: "Salade Brunch", price: 30 },
      { name: "Salade Pecheur", price: 45 },
    ],
  },
  {
    id: "drinks",
    title: "Jus & Drinks",
    items: [
      { name: "Orange", price: 15 },
      { name: "Mangue", price: 20 },
      { name: "Panache", price: 20 },
      { name: "Ananas", price: 20 },
      { name: "Avocat", price: 20 },
      { name: "Pomme", price: 14 },
      { name: "Citron", price: 13 },
      { name: "Banane", price: 14 },
      { name: "Soda", price: 6 },
      { name: "Eau Minerale Small", price: 2 },
      { name: "Eau Minerale Large", price: 7 },
    ],
  },
  {
    id: "dessert",
    title: "Dessert",
    items: [
      { name: "Crepe Nutella", price: 20 },
      { name: "Salade Fruit", price: 18 },
      { name: "Tiramisu", price: 16 },
    ],
  },
];